resources:
  - name:       Git
    type:       GitRepo
    configuration:
      gitProvider:  Git_disha
      path:         dishameswania/pipeline-successful-test   

pipelines:
  - name: clone
    steps:
      - name: clone
        type: Bash
        configuration:
          integrations:
            - name: ssh_disha
        execution:
          onStart:
            - echo 'ssh -o StrictHostKeyChecking=no $*' > "$step_tmp_dir/ssh"
            - chmod +x "$step_tmp_dir/ssh"
            - retry_command ssh-agent bash -c "ssh-add ~/.ssh/ssh_disha; GIT_SSH="$step_tmp_dir/ssh" git clone git@github.com:dishameswania/pipeline-successful-test.git"
            - cd pipeline-successful-test
            - ls
